### ISSUE TITLE
Lottie animation randomly play on some list items with no likes

### ISSUE THREAD

**Issue by merklol** [OyaCanli/tutorial_samples#1]
Hi! I followed your implementation of a custom ItemAnimator on my project. There are occurrences when a Lottie animation can randomly play on some list items with no likes, especially when animations are long(For instance, 2 seconds long).

As far as I understand, it happens because the ItemAnimator re-uses the same ViewHolders and does not notify the RecyclerView about the end of the animation correctly because there is no guarantee that LottieValueAnimator is going to trigger Animator.AnimatorListener.onAnimationEnd callback.

My ItemAnimator looks like this:
```
class SampleItemAnimator : DefaultItemAnimator() {
    override fun animateChange(
        oldHolder: RecyclerView.ViewHolder,
        newHolder: RecyclerView.ViewHolder,
        preInfo: ItemHolderInfo,
        postInfo: ItemHolderInfo
    ): Boolean {
        val holder = newHolder as BindingViewHolder<ItemSampleBinding>
        val animator = lottieAnimatorListener {
            dispatchAnimationFinished(holder)
            holder.binding.sampleAnimation.removeAllAnimatorListeners()
        }
        holder.binding.sampleAnimation.addAnimatorListener(animator)

        if (preInfo is SampleItemHolderInfo) {
            if (preInfo.isItemLicked) {
                holder.binding.sampleAnimation.playAnimation()
            } else {
                resetAnimation(holder.binding.sampleAnimation)
            }
            return false
        }

        return false
    }

    private fun resetAnimation(lottieAnimationView: LottieAnimationView) {
        lottieAnimationView.progress = 0f
        lottieAnimationView.cancelAnimation()
    }

    override fun recordPreLayoutInformation(
        state: RecyclerView.State,
        viewHolder: RecyclerView.ViewHolder,
        changeFlags: Int,
        payloads: MutableList<Any>
    ): ItemHolderInfo {
        if (changeFlags == FLAG_CHANGED) {
            return produceItemHolderInfoOrElse(payloads.firstOrNull() as? Int) {
                super.recordPreLayoutInformation(state, viewHolder, changeFlags, payloads)
            }
        }
        return super.recordPreLayoutInformation(state, viewHolder, changeFlags, payloads)
    }

    private fun produceItemHolderInfoOrElse(value: Int?, action: () -> ItemHolderInfo) =
        when (value) {
            LIKE_ITEM -> SampleItemHolderInfo(true)
            UNLIKE_ITEM -> SampleItemHolderInfo(false)
            else -> action()
        }

    override fun canReuseUpdatedViewHolder(viewHolder: RecyclerView.ViewHolder) = true

    override fun canReuseUpdatedViewHolder(
        viewHolder: RecyclerView.ViewHolder,
        payloads: MutableList<Any>
    ) = true
}
```
That is how I define a ViewHolder using the FastAdapter library:
```
class SampleItem(
    val markableItem: MarkableItem,
    private val onClickItem: (Item) -> Unit
) : AbstractBindingItem<ItemSampleBinding>() {
    override val type: Int = R.layout.item
    override var identifier: Long = markableItem.item.hashCode().toLong()

    override fun createBinding(inflater: LayoutInflater, parent: ViewGroup?) =
        ItemSampleBinding.inflate(inflater, parent, false)

    override fun bindView(binding: ItemSampleBinding, payloads: List<Any>) {
        super.bindView(binding, payloads)
        with(binding) {
            itemName.text = markableItem.item.name
            itemImage.setContent(markableItem.item)
            likeAnimation.progress = if(markableItem.isClicked) 1f else 0f
            root.setThrottleClickListener { onClickItem(markableItem.item) }
        }
    }
}
```

I would appreciate any suggestions on how to deal with it.

**Comment by OyaCanli** [comment]
Hi! One thing that grasped my attention is that you are returning false from animateChange method, which didn't seem correct to me. But I don't think that is the reason of your bug, I tried your animator on my sample with minimal adaptation and it worked fine. 
If the rest is working fine this sounds indeed like a recycling problem. I would try to override onViewRecycled method of the adapter and cancel/clean up animations.. But you say you use a library as adapter.. I don't know how much you can control the adapter..

**Comment by merklol** [comment]
> Hi! One thing that grasped my attention is that you are returning false from animateChange method, which didn't seem correct to me. But I don't think that is the reason of your bug, I tried your animator on my sample with minimal adaptation and it worked fine.
> If the rest is working fine this sounds indeed like a recycling problem. I would try to override onViewRecycled method of the adapter and cancel/clean up animations.. But you say you use a library as adapter.. I don't know how much you can control the adapter..

Thank you very much for your response and for pointing out the incorrect return type. I was experimenting with it and completely forgot to change it back. It seems to work fine now.
